# How to author Executors: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
description: >
  Base CircleCI docker image.
docker:
  - image: 'cimg/base:<<parameters.tag>>'
parameters:
  tag:
    default: stable
    description: >
      Pick a specific cimg/base image tag:
      https://hub.docker.com/r/cimg/base/tags
    type: string
